# Generated by Django 4.1.3 on 2023-06-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="opened",
            field=models.BooleanField(default=True),
        ),
    ]
