# Generated by Django 3.0.6 on 2020-08-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('payment', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='payment',
            new_name='salary',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date',
            field=models.DateField(),
        ),
    ]
